In [2]:
# Variables and Types
# Calculate BMI

height = 1.79
weight = 68.7
BMI = weight / height**2
BMI

21.44127836209856

In [1]:
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

In [2]:
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [3]:
fam[4:]

['mom', 1.71, 'dad', 1.89]

In [4]:
fam[-1]

1.89

In [9]:
fam[-8:]

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [10]:
fam[7] = 1.98

In [11]:
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.98]

In [16]:
def square(x):
    y = x**2
    return y

In [17]:
square(2)

4

In [18]:
square(10)

100

In [26]:
fam2 = [1.73, 1.68, 1.71, 1.98]

In [27]:
max(fam2)

1.98

In [22]:
height = [2, 3, 4, 5, 6, 7, 8, 9]
weight = [2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
import numpy as np
np_height = np.array(height)
np_weight = np.array(weight)
div = np_weight / np_height
div

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
add = np_weight + np_height
add

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
BMI = np_weight / np_height**2
BMI

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     , 0.11111111])

In [28]:
fam2 + fam2

[1.73, 1.68, 1.71, 1.98, 1.73, 1.68, 1.71, 1.98]

In [29]:
import seaborn as sns

In [1]:
pwd

'C:\\Users\\user\\Python for Data Science(DataCamp)'